#!/bin/bash

virtualenv env
source env/bin/activate

if [[ "$CATALOG_ENV" == "dev" ]]; then
    pip install -r dev_requirements.txt
else
    pip install -r requirements.txt
fi

./manage.py dropdb
./manage.py createdb
./manage.py initdb
